DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Bidders;
DROP TABLE IF EXISTS Sellers;
DROP TABLE IF EXISTS Bids;
DROP TABLE IF EXISTS Categories;

CREATE TABLE Items (
	ItemID INTEGER,
	Name CHAR(256),
	Currently DOUBLE,
	Buy_Price DOUBLE,
	First_Bid DOUBLE,
	Number_of_Bids INTEGER,
	Started CHAR(256),
	Ends CHAR(256),
	Seller_UserID CHAR(256),
	Description CHAR(1000),
	PRIMARY KEY(ItemID)
	FOREIGN KEY(Seller_UserID) REFERENCES Sellers(UserID) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE Bidders (
	UserID CHAR(256),
	Rating INTEGER,
	Location CHAR(256),
	Country CHAR(256),
	PRIMARY KEY(UserID)
);

CREATE TABLE Sellers (
	UserID CHAR(256),
	Rating INTEGER,
	Location CHAR(256),
	Country CHAR(256),
	PRIMARY KEY(UserID)
);

CREATE TABLE Bids (
	ItemID INTEGER,
	Bidder_UserID CHAR(256),
	Amount DOUBLE,
	Time CHAR(256),
	PRIMARY KEY(ItemID, Bidder_UserID, Amount),
	UNIQUE (ItemID, Time),
	FOREIGN KEY(ItemID) REFERENCES Items(ItemID) DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY(Bidder_UserID) REFERENCES Bidders(UserID) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE Categories (
	ItemID INTEGER,
	Category CHAR(256),
	PRIMARY KEY(ItemID, Category)
	FOREIGN KEY(ItemID) REFERENCES Items(ItemID) DEFERRABLE INITIALLY DEFERRED
);
